spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: scheduled-service
          uri: lb://scheduled-service
          predicates:
            - Path=/scheduled-service/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
